# Generated by Django 3.2.8 on 2022-02-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20220224_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='free', max_length=10),
            preserve_default=False,
        ),
    ]
