# Generated by Django 3.2.8 on 2022-02-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='category_name',
        ),
    ]
