# Generated by Django 3.2.11 on 2022-01-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('game_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('game_mode', models.CharField(max_length=20)),
                ('champ_level', models.IntegerField()),
                ('champ_name', models.CharField(max_length=20)),
                ('kill', models.IntegerField()),
                ('death', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('CS', models.IntegerField()),
                ('game_result', models.BooleanField()),
                ('play_time', models.IntegerField()),
                ('total_damage', models.IntegerField()),
                ('vision_ward', models.IntegerField()),
            ],
            options={
                'ordering': ['-game_ID'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('summoner_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('summoner_level', models.IntegerField()),
                ('summoner_icon', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailRecord',
            fields=[
                ('game_ID', models.ForeignKey(db_column='game_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='summoner.gamerecord')),
                ('primary_perk', models.IntegerField()),
                ('sub_perk', models.IntegerField()),
                ('item0', models.IntegerField()),
                ('item1', models.IntegerField()),
                ('item2', models.IntegerField()),
                ('item3', models.IntegerField()),
                ('item4', models.IntegerField()),
                ('item5', models.IntegerField()),
                ('item6', models.IntegerField()),
                ('spell1', models.IntegerField()),
                ('spell2', models.IntegerField()),
            ],
            options={
                'ordering': ['-game_ID'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('summoner_name', models.OneToOneField(db_column='summoner_name', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tier', serialize=False, to='summoner.user')),
                ('solo_tier', models.CharField(max_length=20)),
                ('solo_rank', models.CharField(max_length=20)),
                ('solo_wins', models.IntegerField()),
                ('solo_losses', models.IntegerField()),
                ('solo_leaguePoints', models.IntegerField()),
                ('free_tier', models.CharField(max_length=20)),
                ('free_rank', models.CharField(max_length=20)),
                ('free_wins', models.IntegerField()),
                ('free_losses', models.IntegerField()),
                ('free_leaguePoints', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='summoner_name',
            field=models.ForeignKey(db_column='summoner_name', on_delete=django.db.models.deletion.CASCADE, related_name='record', to='summoner.user'),
        ),
    ]
